#!/bin/bash

if [ -n "$1" ]; then
    DEVICE=$1
else
    DEVICE=venu2plus
fi

echo "Testing: $DEVICE"
if [ -d bin ]; then
    rm -Rf bin
fi
mkdir bin

monkeyc -d $DEVICE -f monkey.jungle -o bin/pomodoro-timer.prg -y ~/develop/tools/mokey_c/developer_key --unit-test
connectiq
monkeydo bin/pomodoro-timer.prg $DEVICE -t